FROM eclipse-temurin:25-jdk

WORKDIR /app

COPY pom.xml .

COPY src ./src

RUN chmod +x mvnw 2>/dev/null || true

RUN ./mvnw clean package -DskipTests || mvn clean package -DskipTests

EXPOSE 8080

CMD ["java", "-jar", "target/student-apii-0.0.1-SNAPSHOT.jar"]